In [8]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

%matplotlib inline

In [9]:
dpath = '../data/'
df = pd.read_csv(dpath + 'pipeline_output.csv')
df

,REGIONC,TYPEHUQ,NWEIGHT,HDD65,Climate_Region_Pub,KOWNRENT,YEARMADE,OCCUPYYRANGE,WALLTYPE,ROOFTYPE,...,IECC_Climate_Pub_2B,IECC_Climate_Pub_3A,IECC_Climate_Pub_3B-4B,IECC_Climate_Pub_3C,IECC_Climate_Pub_4A,IECC_Climate_Pub_4C,IECC_Climate_Pub_5A,IECC_Climate_Pub_5B-5C,IECC_Climate_Pub_6A-6B,IECC_Climate_Pub_7A-7B-7AK-8AK
0,2,2,2471.68,4742,4,1,2004,8,1,5,...,0,0,0,0,1,0,0,0,0,0
1,4,2,8599.17,2662,5,2,1998,8,2,2,...,0,0,0,1,0,0,0,0,0,0
2,1,5,8969.92,6233,1,2,1965,7,1,-2,...,0,0,0,0,0,0,1,0,0,0
3,2,2,18003.64,6034,1,1,1985,5,6,5,...,0,0,0,0,0,0,1,0,0,0
4,1,3,5999.61,5388,1,1,1983,5,2,5,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12078,2,2,10219.80,7671,1,1,1985,7,3,6,...,0,0,0,0,0,0,0,0,1,0
12079,3,4,8689.07,2085,2,2,1980,8,1,2,...,0,0,1,0,0,0,0,0,0,0
12080,2,2,4697.21,7935,1,1,1993,7,3,6,...,0,0,0,0,0,0,0,0,1,0
12081,4,2,13155.68,5834,1,1,1930,4,1,6,...,0,0,0,0,0,0,0,1,0,0
12082,4,2,7703.43,2806,5,1,1948,8,2,6,...,0,0,0,1,0,0,0,0,0,0

In [4]:
# note
# corr matrix threshold (elim) (lowe corr matrix)
# plot remaining var with correlation to target, cut agian
# Run PCA... how many? based on eigenvalues... # of PCA comp = # of eigen values 1 or higher. filter to this
# Specify data types... Ordinal / Chat / continous / datetime???
# LR... polly... Dirichlet Reg
# L2 for penalization/generalization
# other alogs? 

# Ideas: 
# convert target into bins? classification....  norm dist bins
#   - Naive Bays... check matrix & Kappa Value(0.9 or higher... robustness of model in real world)
#   - Treat outliners... before / after PCA
# Any feature missing val > .4 eliminate

In [14]:
X = np.array(df.drop('KWH', axis=1))
y = np.array(df['KWH'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=150)

reg = LinearRegression()
reg.fit(X_train, y_train)

print("Train R2:", reg.score(X_train, y_train))
print("Test R2:", reg.score(X_test, y_test))

#display adjusted R-squared
adj_r2_train = 1 - (1-reg.score(X_train, y_train))*(len(y_train)-1)/(len(y_train)-X_train.shape[1]-1)
adj_r2_test = 1 - (1-reg.score(X_test, y_test))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

print("Train Adjusted R2:", adj_r2_train)
print("Test Adjusted R2:", adj_r2_test)

Train R2: 0.9506596211038719
Test R2: 0.9291031403814206
Train Adjusted R2: 0.9476578544500056
Test Adjusted R2: 0.9181490222179892

In [13]:
# again if we scale it? 

X = df.drop('KWH', axis=1)
y = np.array(df['KWH'])

# we should only scale for test data not all otherwise there is data leak with the scale
sc = StandardScaler()
sc.fit_transform(X)
X_scaled = sc.transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
# X_scaled

X = np.array(X_scaled)
y = np.array(df['KWH'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=150)

reg = LinearRegression()
reg.fit(X_train, y_train)

print("Train R2:", reg.score(X_train, y_train))
print("Test R2:", reg.score(X_test, y_test))

#display adjusted R-squared
adj_r2_train = 1 - (1-reg.score(X_train, y_train))*(len(y_train)-1)/(len(y_train)-X_train.shape[1]-1)
adj_r2_test = 1 - (1-reg.score(X_test, y_test))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

print("Train Adjusted R2:", adj_r2_train)
print("Test Adjusted R2:", adj_r2_test)

Train R2: 0.9506536093214442
Test R2: -1.4270044242196544e+24
Train Adjusted R2: 0.9476514769231628
Test Adjusted R2: -1.6474877455788556e+24

In [ ]:
# type compare test

In [28]:
# again if we scale it? #scale with the fit on X_train then apply to X_test 
X = np.array(df.drop('KWH', axis=1))
y = np.array(df['KWH'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=150)

# fit scale on X_train data
sc = StandardScaler()
sc.fit(X_train)
X_train_scaled = sc.transform(X_train)
X_test_scaled = sc.transform(X_test)

# Linear Regression
reg = LinearRegression()
reg.fit(X_train, y_train)

# print scores
print("Train R2:", reg.score(X_train, y_train))
print("Test R2:", reg.score(X_test, y_test))

# display adjusted R-squared
adj_r2_train = 1 - (1-reg.score(X_train, y_train))*(len(y_train)-1)/(len(y_train)-X_train.shape[1]-1)
adj_r2_test = 1 - (1-reg.score(X_test, y_test))*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

print("Train Adjusted R2:", adj_r2_train)
print("Test Adjusted R2:", adj_r2_test)

Train R2: 0.9506596211038719
Test R2: 0.9291031403814206
Train Adjusted R2: 0.9476578544500056
Test Adjusted R2: 0.9181490222179892

numpy.ndarray

In [5]:
# try pycarret

from pycaret.regression import *

In [6]:
s = setup(data = df, target='KWH', n_jobs=-1)

In [7]:
best = compare_models()

In [ ]:
# there is still major data leakage becasue am getting a close to perfect prediction....